language: python
python:
  - "3.7"

before_install:
  - sudo apt-get install -y libxml2-utils

# install:
  # - pip install pipenv
  # - pipenv install --dev

script:
  -  for XML in $(find ms-xml -name '*.xml'); do xmllint --relaxng schema/ms-transcription.rng $XML --noout || error=true; done; if [ $error ]; then exit 1 ; fi
  -  bash check_metadata.sh
  -  bash check_filecount.sh
  -  bash check_filenames.sh

