before_install:
  - sudo apt-get install -y libxml2-utils

script:
  -  for XML in $(find ms-xml -name '*.xml'); do xmllint --relaxng schema/ms-transcription.rng $XML --noout || error=true; done; if [ $error ]; then exit 1 ; fi
  -  test.py


