name: run-ci
on: [push]
jobs:
    xml-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get install -y libxml2-utils
            - run: for XML in $(find ms-xml -name '*.xml'); do xmllint --relaxng schema/ms-transcription.rng $XML --noout || error=true; done; if [ $error ]; then exit 1 ; fi
    check-derivatives:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bash check_metadata.sh
            - run: bash check_filecount.sh
            - run: bash check_filenames.sh
